# Generated by Django 5.2.4 on 2025-08-02 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_text', models.TextField()),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blogs')),
                ('blog_upload_time', models.DateTimeField(auto_now_add=True)),
                ('blog_last_upload_time', models.DateTimeField(auto_now=True)),
                ('blog_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
